<h2>Passwort zurücksetzen</h2>
<p>Hallo <?php echo $this->user->getDisplayName(); ?>!</p>
<p>
    Sie haben auf <a href="<?php echo $this->fullUrl('https'); ?>" title="Startseite"><?php echo $this->fullUrl('https'); ?></a>
    die Zurücksetzung Ihres Passworts angefordert.<br />
    Bitte klicken Sie auf den folgenden Link um die Anfrage zu bestätigen und ein neues Passwort festzulegen:
    <br />
    <a href="<?php echo $this->fullUrl('https').$this->confirmationUrl; ?>" title="Neues Passwort angeben" class="button btn-primary">Neues Passwort angeben</a>
</p>
<p>
    Sollte der Bestätigungslink nicht funktionieren können Sie die Daten auf der Seite
    <a href="<?php echo $this->fullUrl('https').$this->confirmationBase; ?>" title="Manuelle Bestätigung"><?php echo $this->fullUrl('https').$this->confirmationBase; ?></a>
    auch manuell angeben.<br />
    Anfrage-Nr: <b><?php echo $this->validation->getId(); ?></b><br />
    Bestätigungscode: <b><?php echo $this->validation->getToken(); ?></b>
</p>
<p>
    Der Bestätigungslink ist noch <?php echo $this->durationFormat(['seconds' => $this->validationTimeout]); ?> gültig.<br />
    Sollten Sie diese Anfrage nicht vorgenommen haben, so ist keine Aktion erforderlich, sie
    verfällt nach Ablauf der Frist automatisch, wenn die Bestätigung
    nicht bis dahin durchgeführt wurde. Ihr bestehendes Passwort bleibt weiterhin gültig.<br />
</p>