Passwort zurücksetzen

Hallo <?php echo $this->user->getDisplayName(); ?>!
Sie haben auf <?php echo $this->fullUrl('https'); ?> die Zurücksetzung Ihres Passworts angefordert.
Bitte klicken Sie auf den folgenden Link um die Anfrage
zu bestätigen ein neues Passwort festzulegen:

<?php echo $this->fullUrl('https').$this->confirmationUrl; ?>


Sollte der Bestätigungslink nicht funktionieren, können Sie die Daten auf
der Seite <?php echo $this->fullUrl('https').$this->confirmationBase; ?> auch manuell angeben.
Anfrage-Nr: <?php echo $this->validation->getId(); ?>

Bestätigungscode: <?php echo $this->validation->getToken(); ?>


Der Bestätigungslink ist noch <?php echo $this->durationFormat(['seconds' => $this->validationTimeout]); ?> gültig.
Sollten Sie diese Anfrage nicht vorgenommen haben, so ist keine Aktion
erforderlich, sie verfällt nach Ablauf der Frist automatisch, wenn die
Bestätigung nicht bis dahin durchgeführt wurde. Ihr bestehendes Passwort
bleibt weiterhin gültig.