<h3><?php echo $this->translate('view.validation.confirm.heading'); ?></h3>
<p>
    <?php echo $this->translate('view.validation.confirm.intro'); ?>
</p>
<div class="flash-messenger">
    <?php echo $this->flashMessenger()->renderAll(); ?>
</div>

<div class="col-md-5">
    <?php
    $this->form->setAttribute('action', $this->url('validation/confirm'));
    echo $this->formDecorator($this->form);
    ?>
</div>