<h3><?php echo $this->translate('view.user.delete.heading'); ?></h3>
<p>
    <?php echo $this->translate('view.user.delete.intro'); ?>
</p>
<div class="flash-messenger">
    <?php echo $this->flashMessenger()->renderAll(); ?>
</div>

<div class="col-md-5">
    <?php
    $this->form->setAttribute('action', $this->url('user/delete', [
        'id' => $this->user->getId(),
    ]));
    echo $this->formDecorator($this->form);
    ?>
</div>