<h3><?php echo $this->translate('view.user.edit.heading'); ?></h3>
<div class="flash-messenger">
    <?php echo $this->flashMessenger()->renderAll(); ?>
</div>
<p>
    <?php echo $this->translate('view.user.edit.intro'); ?>
</p>

<div class="col-md-5">
    <?php
    $this->form->setAttribute('action', $this->url('user/edit',
        ['id' => $this->user->getId()]));
    echo $this->formDecorator($this->form);
    ?>
</div>