<h3><?php echo $this->translate('view.user.index.heading'); ?></h3>
<p>
    <?php echo $this->translate('view.user.index.intro'); ?>
</p>
<div class="flash-messenger">
    <?php $this->flashMessenger()->renderAll(); ?>
</div>
<a href="<?php echo $this->url('user/create'); ?>" title="<?php echo $this->translate('view.user.gotoCreate'); ?>">
    <?php echo $this->translate('view.user.gotoCreate'); ?>
</a>
<br />

<div class="col-md-5">
    <?php
    $this->form->setAttribute('action', $this->url('user'));
    echo $this->formDecorator($this->form);
    ?>
</div>

<?php if ($this->paginator->count()) : ?>
<div class="clear clearfix"></div>
<a name="users-list"></a>
<table class="table">
    <thead>
        <tr>
            <th>
                <?php echo $this->partial('app-base/partials/sortcolumn', [
                    'field'    => 'username',
                    'label'    => $this->translate('view.user.username'),
                    'orderBy'  => $this->orderBy,
                    'order'    => $this->order,
                    'fragment' => 'users-list',
                ]); ?>
                <br />
                <?php echo $this->translate('view.user.displayName'); ?>
            </th>
            <th>
                <?php echo $this->partial('app-base/partials/sortcolumn', [
                    'field'    => 'email',
                    'label'    => $this->translate('view.user.email'),
                    'orderBy'  => $this->orderBy,
                    'order'    => $this->order,
                    'fragment' => 'users-list',
                ]); ?>
            </th>
            <th>
                <?php echo $this->partial('app-base/partials/sortcolumn', [
                    'field'    => 'lastLogin',
                    'label'    => $this->translate('view.user.lastLogin'),
                    'orderBy'  => $this->orderBy,
                    'order'    => $this->order,
                    'fragment' => 'users-list',
                ]); ?>
            </th>
            <th>
                <?php echo $this->translate('view.user.groups'); ?>
            </th>
            <th>
                <?php echo $this->translate('view.user.isActive'); ?> /
                <?php echo $this->translate('view.user.isValidated'); ?>
            </th>
            <th>
                <?php echo $this->translate('view.actions'); ?>
            </th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($this->paginator as $user) : ?>
        <tr>
            <td>
                <?php echo $user->getUserName(); ?><br />
                <?php echo $user->getDisplayName(); ?>
            </td>
            <td>
                <?php echo $user->getEmail(); ?>
            </td>
            <td>
                <?php echo $this->dateFormat($user->getLastLogin(), IntlDateFormatter::SHORT, IntlDateFormatter::SHORT); ?>
            </td>
            <td>
                <?php
                    foreach($user->getGroups() as $group) {
                        echo $group->getName().'<br />';
                    }
                ?>
            </td>
            <td>
                <?php echo $this->translate($user->getIsActive() ?
                        'view.yes' : 'view.no'); ?> /
                <?php echo $this->translate($user->getIsValidated() ?
                        'view.yes' : 'view.no'); ?>
            </td>
            <td>
                <a href="<?php echo $this->url('user/edit', ['id' => $user->getId()]); ?>" title="<?php echo $this->translate('view.user.gotoEdit'); ?>">
                    <?php echo $this->translate('view.user.gotoEdit'); ?>
                </a>
                <br />
                <a href="<?php echo $this->url('user/delete', ['id' => $user->getId()]); ?>" title="<?php echo $this->translate('view.user.gotoDelete'); ?>">
                    <?php echo $this->translate('view.user.gotoDelete'); ?>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php

echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    'sliding',
    'app-base/partials/paginator.phtml',
    [
        'route'    => 'user',
        'fragment' => 'users-list',
    ]
);

else : ?>
<p>
    <?php echo $this->translate('message.user.noUsersFound'); ?>
</p>
<?php endif;