<h3><?php echo $this->translate(['view.account.changeDisplayName.heading', $this->identity()->getDisplayName()]); ?></h3>
<p>
    <?php echo $this->translate(['view.account.changeDisplayName.intro', $this->identity()->getDisplayName()]); ?>
</p>
<div class="flash-messenger">
    <?php $this->flashMessenger()->renderAll(); ?>
</div>

<div class="col-md-5">
    <?php
        echo $this->formDecorator($this->form);
    ?>
</div>