<h3><?php echo $this->translate(['view.account.delete.heading', $this->currentUser()->getDisplayName()]); ?></h3>
<div class="col-md-5">
    <p>
        <?php echo $this->translate(['view.account.delete.intro', $this->currentUser()->getDisplayName()]); ?>
    </p>
    <div class="flash-messenger">
        <?php $this->flashMessenger()->renderAll(); ?>
    </div>

    <?php
        if ($this->form) {
            echo $this->formDecorator($this->form);
        }
    ?>
</div>