<h3><?php echo $this->translate('view.account.login.heading'); ?></h3>
<p>
    <?php echo $this->translate('view.account.login.intro'); ?>
</p>
<div class="flash-messenger">
    <?php $this->flashMessenger()->renderAll(); ?>
</div>
<div class="row">
    <div class="fourteen columns">
        <?php
            $this->form->setAttribute('action', $this->url('account/login'));
            echo $this->formDecorator($this->form);
        ?>

        <a href="<?php echo $this->url('account/request-password'); ?>" title="<?php echo $this->translate('view.user.gotoPasswordRequest'); ?>">
            <?php echo $this->translate('view.user.gotoPasswordRequest'); ?>
        </a>
    </div>
</div>