<h3><?php echo $this->translate(array('view.account.logout.heading', $this->currentUser()->getDisplayName())); ?></h3>
<p>
    <?php echo $this->translate(array('view.account.logout.intro', $this->currentUser()->getDisplayName())); ?>
</p>
<div class="flash-messenger">
    <?php $this->flashMessenger()->renderAll(); ?>
</div>
<div class="row">
    <div class="fourteen columns">
        <?php
            $this->form->setAttribute('action', $this->url('account/logout'));
            echo $this->formDecorator($this->form);
        ?>
    </div>
</div>