<h3><?php echo $this->translate('view.account.passwordRequest.heading'); ?></h3>
<p>
    <?php echo $this->translate('view.account.passwordRequest.intro'); ?>
</p>
<div class="flash-messenger">
    <?php $this->flashMessenger()->renderAll(); ?>
</div>
<div class="row">
    <div class="fourteen columns">
        <?php
            $this->form->setAttribute('action', $this->url('account/request-password'));
            echo $this->formDecorator($this->form);
        ?>
    </div>
</div>