<h3><?php echo $this->translate('view.admin.caches.heading'); ?></h3>
<p>
    <?php echo $this->translate('view.admin.caches.intro'); ?>
</p>
<div class="flash-messenger">
    <?php echo $this->flashMessenger()->renderAll(); ?>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                <?php echo $this->translate('view.cache.name'); ?>
            </th>
            <th>
                <?php echo $this->translate('view.cache.type'); ?>
            </th>
            <th>
                <?php echo $this->translate('view.cache.status'); ?>
            </th>
            <th>
                <?php echo $this->translate('view.actions'); ?>
            </th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->caches as $name => $cache) : ?>
        <tr>
            <td><?php echo $name; ?></td>
            <td><?php echo str_replace('Zend\Cache\Storage\Adapter\\', '', get_class($cache)); ?></td>
            <td><?php
                /* @var $cache \Zend\Cache\Storage\StorageInterface */
                $o = $cache->getOptions();
                /* @var $o Zend\Cache\Storage\Adapter\MemcachedOptions */
                $s = $o->getServers();
                $m = new Memcache();
                $m->addserver($s[0]['host'], $s[0]['port']);
                $stats = $m->getstats();
                echo round($stats['bytes']/1024).' / '.round($stats['limit_maxbytes']/1024).' kiB belegt<br />';
                echo round($stats['get_hits'] * 100 / $stats['cmd_get']).'% Hit-Ratio<br />';
                echo $stats['curr_items'].' Einträge aktuell, '.$stats['evictions'].' Evictions';

                // @todo wenn (lib)memcached benutzt wird lassen sich die Stats nicht abrufen
                // sie sind entweder leer als wäre der Server nicht erreichbar oder es gibt einen TImeout
                /*if ($cache instanceof \Zend\Cache\Storage\TotalSpaceCapableInterface) {
                    $totalSpace = $cache->getTotalSpace();
                    if ($totalSpace) {
                        echo $totalSpace;

                        if (0 && $cache instanceof \Zend\Cache\Storage\AvailableSpaceCapableInterface) {
                            echo $cache->getAvailableSpace();
                        }
                    } else {
                        echo $this->translate('view.cache.probablyOffline');
                    }
                }*/

            ?></td>
            <td>
                <?php if ($cache instanceof \Zend\Cache\Storage\FlushableInterface) : ?>
                <a class="button btn btn-primary btn-sm"href="<?php echo $this->url('admin/flush-cache', ['name' => $name]); ?>" title="<?php echo $this->translate('view.cache.flush'); ?>">
                    <?php echo $this->translate('view.cache.flush'); ?>
                </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>