<h3><?php echo $this->translate('view.user.group.create.heading'); ?></h3>
<p>
    <?php echo $this->translate('view.user.group.create.intro'); ?>
</p>
<div class="flash-messenger">
    <?php echo $this->flashMessenger()->renderAll(); ?>
</div>

<div class="col-md-5">
    <?php
    $this->form->setAttribute('action', $this->url('user/group/create'));
    echo $this->formDecorator($this->form);
    ?>
</div>